<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
        <TrimmerSingleWarn>false</TrimmerSingleWarn>
        <DebugType>embedded</DebugType>
        <AssemblyVersion>1.2.1.0</AssemblyVersion>
        <InformationalVersion>1.2.1</InformationalVersion>
        <Copyright>Copyright © PurelyAndy 2026</Copyright>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="11.3.16" />
        <PackageReference Include="Avalonia.Desktop" Version="11.3.16" />
        <PackageReference Include="Avalonia.Diagnostics" Version="11.3.16" />
        <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.16" />
        <PackageReference Include="Avalonia.Themes.Simple" Version="11.3.16" />
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
        <PackageReference Include="DialogHost.Avalonia" Version="0.11.0" />
        <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.50.0" />
        <PackageReference Include="Microsoft.CognitiveServices.Speech.Extension.Embedded.SR" Version="1.50.0" />
        <PackageReference Include="Microsoft.CognitiveServices.Speech.Extension.ONNX.Runtime" Version="1.50.0" />
        <PackageReference Include="Microsoft.CognitiveServices.Speech.Extension.Telemetry" Version="1.50.0" />
        <PackageReference Include="org.k2fsa.sherpa.onnx" Version="1.13.2" />
        <PackageReference Include="SharpZipLib" Version="1.4.2" />
        <PackageReference Include="SoundFlow" Version="1.4.1" />
        <PackageReference Include="SoundFlow.Codecs.FFMpeg" Version="1.4.0" />
        <PackageReference Include="System.IO.Ports" Version="11.0.0-preview.4.26230.115" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\AudioConfig.axaml.cs">
        <DependentUpon>AudioConfigView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\SpeechRecognitionMonitor.axaml.cs">
        <DependentUpon>MonitorView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\PhraseList.axaml.cs">
        <DependentUpon>PhraseListView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\ShockerConfig.axaml.cs">
        <DependentUpon>ShockerConfigView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\AboutView.axaml.cs">
        <DependentUpon>AboutView.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Windows\MainWindow.axaml.cs">
        <DependentUpon>MainWindow.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
      <Compile Update="Views\ModelSelection\ModelSelector.axaml.cs">
        <DependentUpon>ModelSelector.axaml</DependentUpon>
        <SubType>Code</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Vosk.Native.Fix\Vosk.Native.Fix.csproj" />
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'linux-x64'">
        <ResolvedFileToPublish Include="$(NuGetPackageRoot)\vosk\0.3.38\build\lib\linux-x64\libvosk.so">
            <RelativePath>libvosk.so</RelativePath>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </ResolvedFileToPublish>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'osx-x64'">
        <ResolvedFileToPublish Include="$(NuGetPackageRoot)\vosk\0.3.38\build\lib\osx-universal\libvosk.dylib">
            <RelativePath>libvosk.dylib</RelativePath>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </ResolvedFileToPublish>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'osx-arm64'">
        <ResolvedFileToPublish Include="$(NuGetPackageRoot)\vosk\0.3.38\build\lib\osx-universal\libvosk.dylib">
            <RelativePath>libvosk.dylib</RelativePath>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </ResolvedFileToPublish>
    </ItemGroup>

    <ItemGroup Condition="'$(RuntimeIdentifier)' == 'win-x64'">
        <ResolvedFileToPublish Include="$(NuGetPackageRoot)\vosk\0.3.38\build\lib\win-x64\libvosk.dll">
            <RelativePath>libvosk.dll</RelativePath>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </ResolvedFileToPublish>

        <ResolvedFileToPublish Include="$(NuGetPackageRoot)\vosk\0.3.38\build\lib\win-x64\libstdc++-6.dll">
            <RelativePath>libstdc++-6.dll</RelativePath>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </ResolvedFileToPublish>

        <ResolvedFileToPublish Include="$(NuGetPackageRoot)\vosk\0.3.38\build\lib\win-x64\libgcc_s_seh-1.dll">
            <RelativePath>libgcc_s_seh-1.dll</RelativePath>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </ResolvedFileToPublish>

        <ResolvedFileToPublish Include="$(NuGetPackageRoot)\vosk\0.3.38\build\lib\win-x64\libwinpthread-1.dll">
            <RelativePath>libwinpthread-1.dll</RelativePath>
            <CopyToPublishDirectory>Always</CopyToPublishDirectory>
        </ResolvedFileToPublish>
    </ItemGroup>
</Project>
